export PATH=$PATH:$HOME/dev/scripts/bash:$HOME/dev/scripts/python:$HOME/dev/bin
export RUST_SRC_PATH=$HOME/dev/rust/src/
export PS1="\
\[\e[00;31m\][\$?, \t]\[\e[0m\]\[\e[00;37m\]::\
\[\e[0m\]\[\e[00;32m\]\u@\h\[\e[0m\]\[\e[00;37m\]::\
\[\e[0m\]\[\e[01;36m\]\w\[\e[0m\]\[\e[00;37m\]\\$ \[\e[0m\]"
