set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'racer-rust/vim-racer'
Plugin 'rust-lang/rust.vim'
call vundle#end()

let g:ycm_auto_start_csharp_server = 0
let g:ycm_confirm_extra_conf = 0
let g:ycm_show_diagnostics_ui = 0
nnoremap <leader>jd :YcmCompleter GoTo<CR>

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_cpp_compiler = 'g++'
let g:syntastic_cpp_compiler_options = '-fconcepts -std=c++1z'
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

highlight LongLine ctermbg=DarkYellow guibg=DarkYellow
highlight WhitespaceEOL ctermbg=DarkYellow guibg=DarkYellow
au BufWinEnter * let w:m0=matchadd('LongLine', '\%>80v.\+', -1)
au BufWinEnter * let w:m1=matchadd('WhitespaceEOL', '\s\+$', -1)
au InsertEnter * call matchdelete(w:m1)
au InsertEnter * let w:m2=matchadd('WhitespaceEOL', '\s\+\%#\@<!$', -1)
au InsertLeave * call matchdelete(w:m2)
au InsertLeave * let w:m1=matchadd('WhitespaceEOL', '\s\+$', -1)

augroup csrc
  au!
  autocmd FileType *      set nocindent smartindent
  autocmd FileType c,cpp  set cindent
augroup END

set cinoptions=:0,g0,(0,Ws,l1

command! DeleteTrailingWs :%s/\s\+$//
command! Untab :%s/\t/  /g

filetype indent plugin on
syntax on
set ignorecase
set smartcase
set wildmenu
set showcmd
set confirm
set backspace=indent,eol,start
set autoindent
set expandtab
set smarttab
set shiftwidth=4
set softtabstop=4

set showmatch
set mat=2
set noerrorbells

set t_Co=256
set colorcolumn=80
"set textwidth=80
"set tw=80
set whichwrap+=<,>,h,l,[,]

set hidden

map <C-K> :pyf /usr/share/vim/addons/syntax/clang-format-3.8.py<cr>
imap <C-K> <c-o>:pyf /usr/share/vim/addons/syntax/clang-format-3.8.py<cr>

vmap <C-c> y:call system("xclip -i -selection clipboard", getreg("\""))<CR>:call system("xclip -i", getreg("\""))<CR>
nmap <C-i> :call setreg("\"",system("xclip -o -selection clipboard"))<CR>p

augroup filetype
  au! BufRead,BufNewFile *.ll     set filetype=llvm
augroup END
augroup filetype
  au! BufRead,BufNewFile *.td     set filetype=tablegen
augroup END

