#!/usr/bin/env bash

elines=3
file="${1%.cpp}"
rest=${@:2}

mainopts="-Ofast -mtune=native -fno-rtti"
restopts="-ftree-vectorize"

OWarn="-Wall -Wextra -Wconversion -pedantic"
OOpts="${mainopts} ${loopopts} ${restopts}"
OOut="-ferror-limit=$elines"

clang++-3.5 -std=c++14 $file.cpp $OWarn $OOpts $OOut $OSec -pthread -o $file $rest
