#!/usr/bin/env bash

sstat() {
    for f in *; do
        [[ -d "$f" ]] && echo `cd "$f"; find|wc -l; cd ..` "$f" || echo "$f"
    done
}

rstat() {
    echo `ls | wc -l` "$PWD";
    for f in *; do
        if [[ -d "$f" ]]; then
            cd "$f"
            rstat
            cd ..
        fi
    done
}

[[ "$1" = "-d" ]] && rstat || sstat
