#!/usr/bin/env bash

source import_except.sh
source import_template.sh

args_or_die "$1"
cd "$experiments_dir" || exit 1
if [[ -f "$1" ]]; then vim "$1" && exit $?
else base=${1%.h}; ext=${1#*.}
    case $ext in
        cpp) cp $template_cpp "$1"                  || exit 1;;
        sh ) cp $template_sh "$1" && chmod u+x "$1" || exit 1;;
        h  ) upper_in=${base^^}
             sed -re "s/STUB/$upper_in/;s/stub/$base/" $template_h > $1;;
        *  ) ;;
    esac
    vim "$1" || exit 1
    exit 0
fi
exit 1
