#!/usr/bin/env bash

source import_except.sh
source import_template.sh

main() {
    args_or_die "$1"
    cd "$experiments_dir"
    if [[ -f "$1" ]]; then vim "$1" && exit 0
    else
        if [[ "$1" == *.cpp ]]; then cp $template_cpp "$1"
        elif [[ "$1" == *.h ]]; then
            base=${1%.h}
            upper_in=${base^^}
            cat $template_h | sed -re s/STUB/"$upper_in"/ | sed -re s/stub/"$base"/ > $1
        fi
        vim "$1" && chmod u+x "$1" && exit 0
    fi
    exit 1
}

main $1
