#!/usr/bin/env bash

source import_except.sh
source import_template.sh

gcsame() {
    [[ ! `diff "$template_dir/template.$1" $2` ]] && {
        echo [I]: rm $2 1>&2; rm $2
    }
}

for f in `ls "$bash_dir"`; do gcsame sh "$bash_dir/$f"; done
