#!/usr/bin/env bash

elines=3
file="${1%.cpp}"
rest=${@:2}

mainopts="-Ofast -mtune=native -fno-rtti"
loopopts="-floop-interchange -ftree-loop-distribution -floop-strip-mine -floop-block"
restopts="-flto=8 -ftree-vectorize"

OWarn="-Wall -Wextra -Wconversion -pedantic"
OOpts="${mainopts} ${loopopts} ${restopts}"
OOut="-fmax-errors=$elines"
OSec="-fstack-protector-all"

g++-5 -std=c++14 $file.cpp $OWarn $OOpts $OOut $OSec -pthread -o $file $rest
