#!/usr/bin/env bash

elines=3
file="${1%.cpp}"
rest=${@:2}

mainopts="-Ofast -mtune=native -fno-rtti -DNDEBUG -s"
loopopts="-floop-interchange -ftree-loop-distribution -floop-strip-mine \
    -floop-block"
restopts="-flto=8 -ftree-vectorize"

OWarn="-Wall -Wextra -Wconversion -pedantic -fno-pretty-templates"
OOpts="${mainopts} ${loopopts} ${restopts}"
OOut="-fmax-errors=$elines"
OSec="-fstack-protector-all"
OTmpl="-ftemplate-depth=50000"

g++-5 -std=c++17 $file.cpp $OWarn $OOpts $OOut $OSec $OTmpl -pthread -o $file $rest
