#!/usr/bin/env bash

case $1 in ''|*[!0-9]*) N=0;  S=$1;;
                     *) N=$1; S=$2;;
esac
file=`[[ $N -gt 1 ]] &&\
    find -type f -iname "*$S*" -printf '%s\t%p\n' | sort -R | head -n$N |\
        sort -rn | awk -F '\t' 'NR==1{print $2}' ||\
    find -type f -iname "*$S*" | sort -R | head -n1`
echo [I]: opening $file 1>&2; poppe "$file"

